---

- name: Create the removable device lookup dictionary
  ansible.builtin.set_fact:
    removable_devices: "{{ removable_devices | default({}) | combine({item : ansible_devices[item].model}) }}"
  when: ansible_devices[item].removable == "1"
  with_items:
    - "{{ ansible_devices.keys() }}"

- name: Create the device menu
  ansible.builtin.set_fact:
    device_menu: |
      {{ device_menu | default('') }}
      Name: {{ item.key }} ({{ item.value }})
  with_dict:
    - "{{ removable_devices }}"

- block:
    - name: Prompt for device to flash
      ansible.builtin.pause:
        prompt: |
          We found the following removable devices:
          {{ device_menu }}
          Please enter the name of the device you want to install on.
      register: device_name
 
    - name: Set device var
      ansible.builtin.set_fact:
        device: "{{ device_name.user_input }}"

  when: device is not defined

- name: Set USB disk path var
  ansible.builtin.set_fact:
    usb_disk_path: "/dev/{{ device }}"

- name: Confirm the device exists and is removable
  ansible.builtin.stat:
    path: "{{ usb_disk_path }}"
  register: usb_disk_stat
  failed_when:
    - not usb_disk_stat.stat.exists or ansible_devices[device].removable != "1"

- name: Get any active mounts
  ansible.builtin.shell:
    cmd: lsblk -no mountpoint {{ usb_disk_path }} | sed '/^$/d'
  register: lsblk_result

- name: Unmount the USB drive
  ansible.posix.mount:
    path: "{{ item }}"
    state: unmounted
  with_items:
    - "{{ lsblk_result.stdout_lines }}"
 
