#!/bin/sh
# Ensure that dm_verity and tools are in the initrd
#

PREREQ=""
prereqs()
{
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

manual_add_modules dm_verity
copy_exec /usr/sbin/veritysetup
copy_exec /usr/sbin/blockdev

# add some filesystem maintenance tools
copy_exec /usr/sbin/lvm
copy_exec /usr/sbin/resize2fs
copy_exec /usr/sbin/reboot
copy_exec /usr/bin/lsblk
